changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Upgraded dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"